blueprint:
  name: Dynamic Notifications to Single Device
  description: Send notifications based on presense detection and use triggers to clear them.
  domain: script
  author: jay-kub
  input:
    device:
      name: Which device would you like to notify?
      default: 
        entity_id: []
      selector:
        device:
          integration: mobile_app
          multiple: false
    person:
      name: Which person is thegit  device tied to?
      default: 
        entity_id: []
      selector:
        target:
          entity:
            domain: person
    only_home:
      name: Notify only if home?
      description: Notifications will only be sent if the person is home.
      default: false
      selector:
        boolean: {}
    only_home_wait:
      name: Notify when home?
      description: If they are away, should the script wait for them to get home and then send a notification?
      default: false
      selector:
        boolean: {}
    clear_notifications:
      name: Trigger to clear notifications?
      description: The script will watch for the trigger below, and once triggered it will clear all notifications and stop the script.
      default: false
      selector:
        boolean: {}    
    clear_trigger:
      name: "Trigger to Clear Notification"
      description: "Leave empty if you don't want the notification to be cleared"
      default: []
      selector:
        trigger:
    notification_tag:
      name: Notification Tag
      description: This tag will be used by home assistant to track the notifications. Please ensure you haven't used the same tag in other automations.
      default: ''

variables:
  device_input: !input device
  device: "{{ device_input.entity_id }}"
  person_input: !input person
  person: "{{ person_input.entity_id }}"
  n_tag: !input notification_tag
  clear_trigger: !input clear_trigger

sequence:
  - parallel:
      - choose:
          - conditions:
              - condition: state
                entity_id: "{{ person }}"
                state: home
            sequence:
              - service: "{{ device }}"
                data:
                  message: "{{ message }}"
                  data:
                    tag: "{{ n_tag }}"
                    # notification_icon: mdi:trash-can-outline
                enabled: true
          - conditions: []
            sequence:
              - wait_for_trigger:
                  - platform: state
                    entity_id:
                      - "{{ person }}"
                    to: home
                timeout:
                  hours: 24
                  minutes: 0
                  seconds: 0
                  milliseconds: 0
                continue_on_timeout: false
              - service: "{{ device }}"
                data:
                  message: "{{ message }}"
                  data:
                    tag: "{{ n_tag }}"
                    # notification_icon: mdi:trash-can-outline
                enabled: true
      - choose:
          - conditions: []
            sequence:
              - wait_for_trigger: "{{ clear_trigger }}" 
              - service: notify.jake_and_ang
                data:
                  data:
                    tag: trash
                  message: clear_notification